import { Body, Controller, Get, Inject, Injectable, Module, NotFoundException, Param, Post } from '@nestjs/common';
import { IsArray, IsBoolean, IsIn, IsMongoId, IsOptional, IsString } from 'class-validator';
import { InjectModel, MongooseModule } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { ExportJob, ExportJobSchema, RestoreJob, RestoreJobSchema } from '@email-backup/database';
import type { QueueRegistry } from '@email-backup/queue';
import { CurrentUser, Roles, type AuthenticatedUser } from './common';
import { InfrastructureModule, QUEUES } from './infrastructure';
class CreateExportDto{@IsArray()@IsMongoId({each:true})mailboxIds!:string[];@IsOptional()@IsArray()@IsMongoId({each:true})messageIds?:string[];@IsIn(['eml','mbox','zip','json','csv'])format!:string;@IsOptional()@IsBoolean()includeAttachments?:boolean;@IsOptional()@IsBoolean()includeMetadata?:boolean;}
class CreateRestoreDto{@IsMongoId()mailboxId!:string;@IsArray()@IsMongoId({each:true})messageIds!:string[];@IsOptional()@IsString()targetFolder?:string;}
@Injectable()class JobsService{constructor(@InjectModel(ExportJob.name)private readonly exports:Model<ExportJob>,@InjectModel(RestoreJob.name)private readonly restores:Model<RestoreJob>,@Inject(QUEUES)private readonly queues:QueueRegistry){}async createExport(dto:CreateExportDto,u:AuthenticatedUser){const doc=await this.exports.create({requestedBy:u.sub,mailboxIds:dto.mailboxIds.map(x=>new Types.ObjectId(x)),messageIds:dto.messageIds?.map(x=>new Types.ObjectId(x)),format:dto.format,includeAttachments:dto.includeAttachments??true,includeMetadata:dto.includeMetadata??true,status:'queued'});await this.queues.get('export').add('export',{exportJobId:String(doc._id)},{jobId:`export:${doc._id}`});return doc}listExports(u:AuthenticatedUser){return this.exports.find({requestedBy:u.sub}).sort({createdAt:-1}).lean()}async getExport(id:string,u:AuthenticatedUser){const d=await this.exports.findOne({_id:id,requestedBy:u.sub}).lean();if(!d)throw new NotFoundException('Export not found');return d}async cancelExport(id:string,u:AuthenticatedUser){const d=await this.exports.findOneAndUpdate({_id:id,requestedBy:u.sub,status:{$in:['queued','running']}},{status:'cancelled'},{new:true});if(!d)throw new NotFoundException('Export not found');return d}async retryExport(id:string,u:AuthenticatedUser){const d=await this.exports.findOneAndUpdate({_id:id,requestedBy:u.sub,status:'failed'},{status:'queued',$unset:{errorCode:1,errorMessage:1}},{new:true});if(!d)throw new NotFoundException('Export not found');await this.queues.get('export').add('export',{exportJobId:id},{jobId:`export:${id}:${Date.now()}`});return d}async createRestore(dto:CreateRestoreDto,u:AuthenticatedUser){const d=await this.restores.create({requestedBy:u.sub,mailboxId:dto.mailboxId,messageIds:dto.messageIds,targetFolder:dto.targetFolder??'Recovered Email Backup',status:'queued'});await this.queues.get('restore').add('restore',{restoreJobId:String(d._id)},{jobId:`restore:${d._id}`});return d}listRestores(u:AuthenticatedUser){return this.restores.find({requestedBy:u.sub}).sort({createdAt:-1}).lean()}async getRestore(id:string,u:AuthenticatedUser){const d=await this.restores.findOne({_id:id,requestedBy:u.sub}).lean();if(!d)throw new NotFoundException('Restore not found');return d}}
@Controller('api/exports')@Roles('super_admin','admin','auditor')class ExportController{constructor(private readonly s:JobsService){}@Post()create(@Body()d:CreateExportDto,@CurrentUser()u:AuthenticatedUser){return this.s.createExport(d,u)}@Get()list(@CurrentUser()u:AuthenticatedUser){return this.s.listExports(u)}@Get(':id')get(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.getExport(id,u)}@Post(':id/cancel')cancel(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.cancelExport(id,u)}@Post(':id/retry')retry(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.retryExport(id,u)}}
@Controller('api/restores')@Roles('super_admin','admin')class RestoreController{constructor(private readonly s:JobsService){}@Post()create(@Body()d:CreateRestoreDto,@CurrentUser()u:AuthenticatedUser){return this.s.createRestore(d,u)}@Get()list(@CurrentUser()u:AuthenticatedUser){return this.s.listRestores(u)}@Get(':id')get(@Param('id')id:string,@CurrentUser()u:AuthenticatedUser){return this.s.getRestore(id,u)}}
@Module({imports:[InfrastructureModule,MongooseModule.forFeature([{name:ExportJob.name,schema:ExportJobSchema},{name:RestoreJob.name,schema:RestoreJobSchema}])],providers:[JobsService],controllers:[ExportController,RestoreController]})export class JobsModule{}
