global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: email-backup-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:3000"]
  - job_name: email-backup-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["worker:3002"]
  - job_name: email-backup-scheduler
    metrics_path: /metrics
    static_configs:
      - targets: ["scheduler:3003"]
